### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by patsanchique** [ddPn08/automatic1111-colab#11]
/content/stable-diffusion-webui
Already up to date.
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Commit hash: 828438b4a190759807f9054932cae3a8b880ddf1
Installing requirements for Web UI
Launching Web UI with arguments: --ckpt-dir /content/drive/MyDrive/AI/models --ui-config-file /content/drive/MyDrive/AI/automatic1111/config/ui-config.json --ui-settings-file /content/drive/MyDrive/AI/automatic1111/config/config.json --styles-file /content/drive/MyDrive/AI/automatic1111/config/styles.csv --deepdanbooru --xformers --share --enable-console-prompts
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 251, in <module>
    start()
  File "/content/stable-diffusion-webui/launch.py", line 242, in start
    import webui
  File "/content/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import devices, sd_samplers, upscaler, extensions, localization
  File "/content/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/stable-diffusion-webui/modules/shared.py", line 8, in <module>
    import gradio as gr
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/gradio/components.py", line 32, in <module>
    from gradio.blocks import Block
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/gradio/blocks.py", line 32, in <module>
    from gradio import (
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/gradio/networking.py", line 19, in <module>
    from gradio.tunneling import create_tunnel
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/gradio/tunneling.py", line 17, in <module>
    import paramiko
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/paramiko/transport.py", line 92, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/paramiko/ed25519key.py", line 22, in <module>
    import nacl.signing
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/nacl/signing.py", line 16, in <module>
    import nacl.bindings
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/nacl/bindings/__init__.py", line 16, in <module>
    from nacl.bindings.crypto_aead import (
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/nacl/bindings/crypto_aead.py", line 17, in <module>
    from nacl._sodium import ffi, lib
ImportError: /usr/local/envs/automatic/lib/python3.10/site-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so: symbol ffi_type_uint32 version LIBFFI_BASE_7.0 not defined in file libffi.so.7 with link time reference

UPD: Error is gone with turned on gradio app authentication

**Comment by patsanchique** [comment]
upd: Error is gone with turned on gradio app authentication

**Comment by ddPn08** [comment]
I can't reproduce this error now due to the updated implementation. If you continue to have problems, please open a new issue again.
