### ISSUE TITLE
Fatal error installing xformers

### ISSUE THREAD

**Issue by TheRepSter** [ddPn08/automatic1111-colab#5]
If I run the "Setup enviroment" I get this error:
```
ERROR: HTTP error 404 while getting https://github.com/ddPn08/automatic1111-colab/blob/main/xformers/T4/xformers-0.0.13.dev0-py3-none-any.whl?raw=true
ERROR: Could not install requirement xformers==0.0.13.dev0 from https://github.com/ddPn08/automatic1111-colab/blob/main/xformers/T4/xformers-0.0.13.dev0-py3-none-any.whl?raw=true because of HTTP error 404 Client Error: Not Found for url: https://github.com/ddPn08/automatic1111-colab/blob/main/xformers/T4/xformers-0.0.13.dev0-py3-none-any.whl?raw=true for URL https://github.com/ddPn08/automatic1111-colab/blob/main/xformers/T4/xformers-0.0.13.dev0-py3-none-any.whl?raw=true
/content/stable-diffusion-webui
Python 3.10.8 (main, Oct 12 2022, 19:14:09) [GCC 7.5.0]
Commit hash: 1b91cbbc1163d3613aa329bed3aecd8e29ca52ca
Installing xformers
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/content/stable-diffusion-webui/launch.py", line 163, in prepare_enviroment
    run_pip("install xformers", "xformers")
  File "/content/stable-diffusion-webui/launch.py", line 62, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/content/stable-diffusion-webui/launch.py", line 33, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install xformers.
Command: "/usr/bin/python3" -m pip install xformers --prefer-binary
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xformers
  Using cached xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Then, if I try running the "Run script" I get this:
```
Already up to date.
Python 3.10.8 (main, Oct 12 2022, 19:14:09) [GCC 7.5.0]
Commit hash: 1b91cbbc1163d3613aa329bed3aecd8e29ca52ca
Installing xformers
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 199, in <module>
    prepare_enviroment()
  File "/content/stable-diffusion-webui/launch.py", line 163, in prepare_enviroment
    run_pip("install xformers", "xformers")
  File "/content/stable-diffusion-webui/launch.py", line 62, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/content/stable-diffusion-webui/launch.py", line 33, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install xformers.
Command: "/usr/bin/python3" -m pip install xformers --prefer-binary
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xformers
  Using cached xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
And then it stops the cell. What can it be? I'm using the colab notebook as it is on the repo.

**Comment by ddPn08** [comment]
The notebook may be out of date due to a mistake I made a while ago. Try reloading and checking against the repository notebook before running.

**Comment by TheRepSter** [comment]
Now working, thx!
