### ISSUE TITLE
Installing torch and torchvision connection error

### ISSUE THREAD

**Issue by ernest88** [ddPn08/automatic1111-colab#59]
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://download.pytorch.org/whl/cu117
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff26ac75180>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu117/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff26ac756f0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu117/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff26ac758a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu117/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff26ac75a50>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu117/torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff26ac75c00>: Failed to establish a new connection: [Errno -2] Name or service not known')': /whl/cu117/torch/
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0)
ERROR: No matching distribution found for torch==1.13.1+cu117
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/content/stable-diffusion-webui/launch.py", line 257, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "/content/stable-diffusion-webui/launch.py", line 81, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "/opt/conda/bin/python" -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
Error code: 1

**Comment by hamnv** [comment]
This caused because original SD web ui has been upgrade for torch 2.0.0. I sovled it by use older version of SD webui
