### ISSUE TITLE
Image generation fails after using DeepDanbooru

### ISSUE THREAD

**Issue by ddPn08** [ddPn08/automatic1111-colab#6]
as the title says. May be related to https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2202
I don't know the cause myself, so I'd like some advice from an expert.

**Comment by ddPn08** [comment]
Error message
```
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/ui.py", line 212, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/webui.py", line 63, in f
    res = func(*args, **kwargs)
  File "/content/stable-diffusion-webui/modules/txt2img.py", line 44, in txt2img
    processed = process_images(p)
  File "/content/stable-diffusion-webui/modules/processing.py", line 400, in process_images
    uc = prompt_parser.get_learned_conditioning(shared.sd_model, len(prompts) * [p.negative_prompt], p.steps)
  File "/content/stable-diffusion-webui/modules/prompt_parser.py", line 138, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "/content/stable-diffusion-webui/repositories/stable-diffusion/ldm/models/diffusion/ddpm.py", line 558, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "/usr/local/envs/automatic/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stable-diffusion-webui/modules/sd_hijack.py", line 334, in forward
    z1 = self.process_tokens(tokens, multipliers)
  File "/content/stable-diffusion-webui/modules/sd_hijack.py", line 349, in process_tokens
    tokens = torch.asarray(remade_batch_tokens).to(device)
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by R-N** [comment]
I'm having the same issue on Google Colab. The deepdanbooru succeeds identifying tags. But this happened and nothing can be done. Simply interrupting then running the cell won't do. Need to restart runtime.

**Comment by ddPn08** [comment]
The error I see in the log before running deepdanbooru.
```
I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-22 00:49:04.885002: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-22 00:49:06.807734: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/envs/automatic/lib/python3.10/site-packages/cv2/../../lib64:/usr/lib64-nvidia
2022-10-22 00:49:06.807992: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/envs/automatic/lib/python3.10/site-packages/cv2/../../lib64:/usr/lib64-nvidia
2022-10-22 00:49:06.808015: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-10-22 00:49:08.913397: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED: initialization error
2022-10-22 00:49:08.913483: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: a808fdee6a81
2022-10-22 00:49:08.913501: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: a808fdee6a81
2022-10-22 00:49:08.913625: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: NOT_FOUND: was unable to find libcuda.so DSO loaded into this program
2022-10-22 00:49:08.913669: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.32.3
2022-10-22 00:49:08.914054: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-22 00:49:13.114835: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 37748736 exceeds 10% of free system memory.
2022-10-22 00:49:13.339996: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 37748736 exceeds 10% of free system memory.
2022-10-22 00:49:13.380794: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 37748736 exceeds 10% of free system memory.
2022-10-22 00:49:13.442729: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 16777216 exceeds 10% of free system memory.
2022-10-22 00:49:13.515808: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 16777216 exceeds 10% of free system memory.
```

**Comment by ddPn08** [comment]
It seems to be related to this issue as well.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2404

**Comment by ddPn08** [comment]
This will probably fix it, but there doesn't seem to be a way to fully automate it.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2404#issuecomment-1288107617

**Comment by ddPn08** [comment]
This was an easier problem than I imagined.
Fixed in this commit.
https://github.com/ddPn08/automatic1111-colab/commit/eccf9ef67466b7969ebff47e20a2b2b47e80ee15
